TG_TOKEN = 'YOUR_TG_TOKEN'
OPEN_WEATHER_KEY = 'YOUR_OPEN_WEATHER_KEY'
with open('yoomoney_token.txt') as f:
    YOOMONEY_TOKEN = f.read().strip()
YOOMONEY_RECEIVER = 'YOUR_YOOMONEY_NUMBER'
ADMIN_IDS = (0,)
